// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace AEBestGatePath.Web.Client.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class Stop : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The distanceToNext property</summary>
        public double? DistanceToNext { get; set; }
        /// <summary>The gameVersion property</summary>
        public double? GameVersion { get; set; }
        /// <summary>The next property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::AEBestGatePath.Web.Client.Models.Stop? Next { get; set; }
#nullable restore
#else
        public global::AEBestGatePath.Web.Client.Models.Stop Next { get; set; }
#endif
        /// <summary>The node property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::AEBestGatePath.Web.Client.Models.Astro? Node { get; set; }
#nullable restore
#else
        public global::AEBestGatePath.Web.Client.Models.Astro Node { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::AEBestGatePath.Web.Client.Models.Stop"/> and sets the default values.
        /// </summary>
        public Stop()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::AEBestGatePath.Web.Client.Models.Stop"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::AEBestGatePath.Web.Client.Models.Stop CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::AEBestGatePath.Web.Client.Models.Stop();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "distanceToNext", n => { DistanceToNext = n.GetDoubleValue(); } },
                { "gameVersion", n => { GameVersion = n.GetDoubleValue(); } },
                { "next", n => { Next = n.GetObjectValue<global::AEBestGatePath.Web.Client.Models.Stop>(global::AEBestGatePath.Web.Client.Models.Stop.CreateFromDiscriminatorValue); } },
                { "node", n => { Node = n.GetObjectValue<global::AEBestGatePath.Web.Client.Models.Astro>(global::AEBestGatePath.Web.Client.Models.Astro.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteDoubleValue("distanceToNext", DistanceToNext);
            writer.WriteDoubleValue("gameVersion", GameVersion);
            writer.WriteObjectValue<global::AEBestGatePath.Web.Client.Models.Stop>("next", Next);
            writer.WriteObjectValue<global::AEBestGatePath.Web.Client.Models.Astro>("node", Node);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
