// <auto-generated/>
#pragma warning disable CS0618
using AEBestGatePath.API.Client.Auth.Redirect;
using AEBestGatePath.API.Client.Auth.Signin;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace AEBestGatePath.API.Client.Auth
{
    /// <summary>
    /// Builds and executes requests for operations under \auth
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class AuthRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The redirect property</summary>
        public global::AEBestGatePath.API.Client.Auth.Redirect.RedirectRequestBuilder Redirect
        {
            get => new global::AEBestGatePath.API.Client.Auth.Redirect.RedirectRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The signin property</summary>
        public global::AEBestGatePath.API.Client.Auth.Signin.SigninRequestBuilder Signin
        {
            get => new global::AEBestGatePath.API.Client.Auth.Signin.SigninRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::AEBestGatePath.API.Client.Auth.AuthRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public AuthRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/auth", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::AEBestGatePath.API.Client.Auth.AuthRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public AuthRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/auth", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
