// <auto-generated/>
#pragma warning disable CS0618
using AEBestGatePath.API.Client.Auth.Redirect.Google;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace AEBestGatePath.API.Client.Auth.Redirect
{
    /// <summary>
    /// Builds and executes requests for operations under \auth\redirect
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class RedirectRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The google property</summary>
        public global::AEBestGatePath.API.Client.Auth.Redirect.Google.GoogleRequestBuilder Google
        {
            get => new global::AEBestGatePath.API.Client.Auth.Redirect.Google.GoogleRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::AEBestGatePath.API.Client.Auth.Redirect.RedirectRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public RedirectRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/auth/redirect", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::AEBestGatePath.API.Client.Auth.Redirect.RedirectRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public RedirectRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/auth/redirect", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
