// <auto-generated/>
#pragma warning disable CS0618
using AEBestGatePath.API.Client.Auth.Signin.Google;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace AEBestGatePath.API.Client.Auth.Signin
{
    /// <summary>
    /// Builds and executes requests for operations under \auth\signin
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class SigninRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The google property</summary>
        public global::AEBestGatePath.API.Client.Auth.Signin.Google.GoogleRequestBuilder Google
        {
            get => new global::AEBestGatePath.API.Client.Auth.Signin.Google.GoogleRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::AEBestGatePath.API.Client.Auth.Signin.SigninRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public SigninRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/auth/signin", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::AEBestGatePath.API.Client.Auth.Signin.SigninRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public SigninRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/auth/signin", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
